[package]
name = "colorlull-render"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "render"

[lints]
workspace = true

[dependencies]
colorlull-colorpack = { workspace = true }
colorlull-stroke = { workspace = true }
bytemuck = { workspace = true }
png = { workspace = true }
thiserror = { workspace = true }
wgpu = { workspace = true }

[dev-dependencies]
png = { workspace = true }
