[package]
name = "colorlull-baker"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "baker"
path = "src/lib.rs"

[[bin]]
name = "baker"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
colorlull-colorpack = { workspace = true }
jpeg-encoder = { workspace = true }
png = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
